input:
  forecasts_dir: "outputs/forecasts"

output:
  base_dir: "analysis_output"

analysis:
  benchmark_model: "ar-qr_T192"  # Model to use as benchmark for DM tests
  mcs_alpha: 0.1  # Significance level for Model Confidence Set

plots:
  separate_quantiles: false   # If true, create separate plots for each quantile
  high_quality: false        # If true, use high DPI and PDF format

covid:
  start_date: "2020-03-01"
  end_date: "2021-12-31"
