seed: 123

data:
  path: processed_per_country
  target: INFL_OECD
  required_columns: []
  lags: []
  horizons: [1]
  quantiles: [0.1]
  missing: forward_fill_then_mean   # or interpolate_linear | drop
  scale: per_country                # or global | none
  scale_target: false
  frequency: infer                  # assert equal spacing
  trimming: true


splits:
  validation_size: 0.3             # fraction of each country's data for validation
  train_start: "2000-2-01"
  test_cutoff: "2017-12-01"         # last date in training; all later dates are test
  min_train_points: 12              # enforce minimum per country

ensemble_nn:
  units_per_layer: [32,16, 8, 4, 2]
  activation: relu
  optimizer: adam
  learning_rate: 1.0e-4
  epochs: 750
  batch_size: 32
  patience: 100
  parallel_models: 10
  per_country: false
  device: auto   
  country_dummies: false                   # cuda if available
  l2_penalty: 0.001 

lqr:
  alphas: [0.0, 0.001, 0.01,0.05, 0.1, 0.5, 1, 2.5, 5]
  solver: huberized
  rff_features: 1000

output:
  save_predictions: true
  save_factors: true
  save_models: true
