seed: 123

data:
  path: processed_per_country
  target: prc_hicp_manr_CP00
  required_columns: []
  lags: []
  horizons: [1]
  quantiles: [0.1]
  missing: forward_fill_then_mean   # or interpolate_linear | drop
  scale: per_country                # or global | none
  scale_target: false
  frequency: infer                  # assert equal spacing
  trimming: true

splits:
  validation_size: 0.3             # fraction of each country's data for validation
  train_start: "1997-01-01"
  test_cutoff: "2016-01-01"         # last date in training; all later dates are test
  min_train_points: 12              # enforce minimum per country

ensemble_nn:
  units_per_layer: [32,32,32,32,32]
  activation: relu
  optimizer: adam
  learning_rate: 5.0e-5
  epochs: 1500
  batch_size: 32
  patience: 50
  parallel_models: 10
  per_country: false
  device: auto   
  country_dummies: false                   # cuda if available
  l2_penalty: 0.0001 

lqr:
  alphas: [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80]
  solver: huberized
  rff_features: 1000
  rolling: false

output:
  save_predictions: true
  save_factors: true
  save_models: true
