seed: 123

data:
  path: processed_per_country
  target: prc_hicp_manr_CP00   
  required_columns: []
  lags: []
  horizons: [1]
  quantiles: [0.9]
  missing: forward_fill_then_mean   # or interpolate_linear | drop
  scale: per_country                # or global | none
  scale_target: false
  frequency: infer                  # assert equal spacing
  trimming: false
  old: prc_hicp_manr_CP00, sts_inpr_m_B-D  

splits:
  validation_size: 0.3             # fraction of each country's data for validation
  train_start: "2004-05-01"
  test_cutoff: "2016-01-01"         # last date in training; all later dates are test
  min_train_points: 12              # enforce minimum per country

ensemble_nn:
  units_per_layer: [32,32,32,32,32]
  activation: relu
  optimizer: adam
  learning_rate: 5.0e-5
  epochs: 1500
  batch_size: 32
  patience: 5
  parallel_models: 10
  per_country: false
  device: auto   
  country_dummies: false                   # cuda if available
  l2_penalty: 0.0 
  turn_on_neural_net: true

lqr:
  alphas: [ 80]
  solver: pinball
  rff_features: 1000
  rolling: false

output:
  save_predictions: true
  save_factors: true
  save_models: true
